/* file: constants.h
   --------------------
   the constants required for the Connect 4 assignment. 
   DO NOT EDIT THIS FILE!!!

   You can declare additional constants, but if you do please do so in
   Connect4.h rather than in this file.
   */

#ifndef CONNECT_4_CONSTANTS
#define CONNECT_4_CONSTANTS

#include <string>

// Note: you MUST consistently use these constants in your program.
// Implementations that don't use these constants will fail several of
// the functionality tests.
const char EMPTY_SQUARE = '-';
const char PLAYER_ONE_PIECE = 'x';
const char PLAYER_TWO_PIECE = 'o';
const size_t ROWS = 8;
const size_t COLUMNS = 8;
const size_t WIN_COUNT = 4;
const std::string PLAYER_ONE_WIN_MESSAGE = "Player 1 has won!"; 
const std::string PLAYER_TWO_WIN_MESSAGE = "Player 2 has won!";
const std::string DRAW_MESSAGE = "Game ended by draw";
const std::string BAD_COLUMN_MESSAGE = "Invalid column";

enum Player {PLAYER_ONE, PLAYER_TWO};

#endif
